USE taxation_db;
SELECT * FROM TAXPAYER;
SELECT * FROM INCOME_RECORD;
SELECT * FROM FINANCIAL_YEAR;
SELECT * FROM INCOME_CATEGORY; 
SELECT UPPER(full_name) AS UPPERCASE_NAME FROM TAXPAYER;
SELECT LOWER(occupation) AS LOWERCASE_OCCUPATION FROM TAXPAYER;
SELECT full_name,LENGTH(full_name) AS NAME_LENGTH FROM TAXPAYER;
SELECT LEFT(pan_num,4) AS PAN_FIRST4 FROM TAXPAYER;
SELECT LEFT(taxpayer_id,4) AS ID_FIRST4 FROM TAXPAYER;
SELECT CONCAT(full_name,' - ',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;

SELECT REPLACE(category_name,'INCOME','Inc.') AS UPDATED_CATEGORY FROM INCOME_CATEGORY;
SELECT SUBSTRING_INDEX(full_name,' ',1) AS FIRST_NAME FROM TAXPAYER;

SELECT CONCAT('TAXPAYER:',full_name,'| OCCUPATION:',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;
SELECT * FROM TAXPAYER WHERE pan_num LIKE 'AP%';

SELECT AMOUNT, ROUND(AMOUNT) AS ROUNDED_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,ABS(AMOUNT-500000) AS ABSOLUTE_DIFF FROM INCOME_RECORD;
SELECT AMOUNT,POW(AMOUNT,2) AS SQUARE_OF_AMOUNT FROM INCOME_RECORD;

SELECT AMOUNT,MOD(AMOUNT,1000) AS REMAINDER FROM INCOME_RECORD;
SELECT AMOUNT,ROUND(AMOUNT,2) AS ROUNDED_INCOME FROM INCOME_RECORD;
SELECT AMOUNT,CEIL(AMOUNT) AS CEILING_VALUE,FLOOR(AMOUNT) AS FLOOR_VALUE FROM INCOME_RECORD;

SELECT FLOOR(RAND() *100) +1 AS RANDOM_NUM;
SELECT AMOUNT,SQRT(AMOUNT) AS SQUAREROOT_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,AMOUNT*1.10 AS INCOME_BY_10PERCENT_INCREMENT FROM INCOME_RECORD;

SELECT CURDATE() AS TODAY_DATE;
SELECT NOW() AS CURRENT_DATE_TIME;
SELECT START_DATE,YEAR(START_DATE) AS YEAR FROM FINANCIAL_YEAR;
SELECT START_DATE,MONTH(START_DATE) AS MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DAY(START_DATE) AS DAY_OF_MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DATE_ADD(START_DATE,INTERVAL 30 DAY) AS DATE_AFTER_30_DAYS FROM FINANCIAL_YEAR;
SELECT START_DATE, DATE_SUB(START_DATE,INTERVAL 7 DAY) AS DATE_BEFORE_7_DAYS FROM FINANCIAL_YEAR;
SELECT YEAR_LABEL,DATEDIFF(CURDATE(),START_DATE) AS DAYS_DIFF FROM FINANCIAL_YEAR;
SELECT * FROM FINANCIAL_YEAR WHERE YEAR (START_DATE)=YEAR(CURDATE());

SELECT CAST(AMOUNT AS SIGNED) AS INCOME_INTEGER FROM INCOME_RECORD;
SELECT CAST(taxpayer_id AS CHAR) AS TAXPAYER_ID_CHAR FROM TAXPAYER;
SELECT CAST(START_DATE AS DATETIME) AS START_DATETIME FROM FINANCIAL_YEAR;
SELECT CAST(AMOUNT AS DECIMAL(10,2)) AS INCOME_DECIMAL FROM INCOME_RECORD;
SELECT CAST(AMOUNT AS CHAR) AS INCOME_STRING FROM INCOME_RECORD;
SELECT taxpayer_id,CAST(AMOUNT AS DECIMAL(10,2))*0.10 AS TAX_AMOUNT FROM INCOME_RECORD;USE DBMSLAB;
SELECT * FROM TAXPAYER;
SELECT * FROM INCOME_RECORD;
SELECT * FROM FINANCIAL_YEAR;
SELECT * FROM INCOME_CATEGORY; 
SELECT UPPER(full_name) AS UPPERCASE_NAME FROM TAXPAYER;
SELECT LOWER(occupation) AS LOWERCASE_OCCUPATION FROM TAXPAYER;
SELECT full_name,LENGTH(full_name) AS NAME_LENGTH FROM TAXPAYER;
SELECT LEFT(pan_num,4) AS PAN_FIRST4 FROM TAXPAYER;
SELECT LEFT(taxpayer_id,4) AS ID_FIRST4 FROM TAXPAYER;
SELECT CONCAT(full_name,' - ',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;

SELECT REPLACE(category_name,'INCOME','Inc.') AS UPDATED_CATEGORY FROM INCOME_CATEGORY;
SELECT SUBSTRING_INDEX(full_name,' ',1) AS FIRST_NAME FROM TAXPAYER;

SELECT CONCAT('TAXPAYER:',full_name,'| OCCUPATION:',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;
SELECT * FROM TAXPAYER WHERE pan_num LIKE 'AP%';

SELECT AMOUNT, ROUND(AMOUNT) AS ROUNDED_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,ABS(AMOUNT-500000) AS ABSOLUTE_DIFF FROM INCOME_RECORD;
SELECT AMOUNT,POW(AMOUNT,2) AS SQUARE_OF_AMOUNT FROM INCOME_RECORD;

SELECT AMOUNT,MOD(AMOUNT,1000) AS REMAINDER FROM INCOME_RECORD;
SELECT AMOUNT,ROUND(AMOUNT,2) AS ROUNDED_INCOME FROM INCOME_RECORD;
SELECT AMOUNT,CEIL(AMOUNT) AS CEILING_VALUE,FLOOR(AMOUNT) AS FLOOR_VALUE FROM INCOME_RECORD;

SELECT FLOOR(RAND() *100) +1 AS RANDOM_NUM;
SELECT AMOUNT,SQRT(AMOUNT) AS SQUAREROOT_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,AMOUNT*1.10 AS INCOME_BY_10PERCENT_INCREMENT FROM INCOME_RECORD;

SELECT CURDATE() AS TODAY_DATE;
SELECT NOW() AS CURRENT_DATE_TIME;
SELECT START_DATE,YEAR(START_DATE) AS YEAR FROM FINANCIAL_YEAR;
SELECT START_DATE,MONTH(START_DATE) AS MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DAY(START_DATE) AS DAY_OF_MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DATE_ADD(START_DATE,INTERVAL 30 DAY) AS DATE_AFTER_30_DAYS FROM FINANCIAL_YEAR;
SELECT START_DATE, DATE_SUB(START_DATE,INTERVAL 7 DAY) AS DATE_BEFORE_7_DAYS FROM FINANCIAL_YEAR;
SELECT YEAR_LABEL,DATEDIFF(CURDATE(),START_DATE) AS DAYS_DIFF FROM FINANCIAL_YEAR;
SELECT * FROM FINANCIAL_YEAR WHERE YEAR (START_DATE)=YEAR(CURDATE());

SELECT CAST(AMOUNT AS SIGNED) AS INCOME_INTEGER FROM INCOME_RECORD;
SELECT CAST(taxpayer_id AS CHAR) AS TAXPAYER_ID_CHAR FROM TAXPAYER;
SELECT CAST(START_DATE AS DATETIME) AS START_DATETIME FROM FINANCIAL_YEAR;
SELECT CAST(AMOUNT AS DECIMAL(10,2)) AS INCOME_DECIMAL FROM INCOME_RECORD;
SELECT CAST(AMOUNT AS CHAR) AS INCOME_STRING FROM INCOME_RECORD;
SELECT taxpayer_id,CAST(AMOUNT AS DECIMAL(10,2))*0.10 AS TAX_AMOUNT FROM INCOME_RECORD;USE DBMSLAB;
SELECT * FROM TAXPAYER;
SELECT * FROM INCOME_RECORD;
SELECT * FROM FINANCIAL_YEAR;
SELECT * FROM INCOME_CATEGORY; 
SELECT UPPER(full_name) AS UPPERCASE_NAME FROM TAXPAYER;
SELECT LOWER(occupation) AS LOWERCASE_OCCUPATION FROM TAXPAYER;
SELECT full_name,LENGTH(full_name) AS NAME_LENGTH FROM TAXPAYER;
SELECT LEFT(pan_num,4) AS PAN_FIRST4 FROM TAXPAYER;
SELECT LEFT(taxpayer_id,4) AS ID_FIRST4 FROM TAXPAYER;
SELECT CONCAT(full_name,' - ',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;

SELECT REPLACE(category_name,'INCOME','Inc.') AS UPDATED_CATEGORY FROM INCOME_CATEGORY;
SELECT SUBSTRING_INDEX(full_name,' ',1) AS FIRST_NAME FROM TAXPAYER;

SELECT CONCAT('TAXPAYER:',full_name,'| OCCUPATION:',occupation) AS TAXPAYER_DETAILS FROM TAXPAYER;
SELECT * FROM TAXPAYER WHERE pan_num LIKE 'AP%';

SELECT AMOUNT, ROUND(AMOUNT) AS ROUNDED_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,ABS(AMOUNT-500000) AS ABSOLUTE_DIFF FROM INCOME_RECORD;
SELECT AMOUNT,POW(AMOUNT,2) AS SQUARE_OF_AMOUNT FROM INCOME_RECORD;

SELECT AMOUNT,MOD(AMOUNT,1000) AS REMAINDER FROM INCOME_RECORD;
SELECT AMOUNT,ROUND(AMOUNT,2) AS ROUNDED_INCOME FROM INCOME_RECORD;
SELECT AMOUNT,CEIL(AMOUNT) AS CEILING_VALUE,FLOOR(AMOUNT) AS FLOOR_VALUE FROM INCOME_RECORD;

SELECT FLOOR(RAND() *100) +1 AS RANDOM_NUM;
SELECT AMOUNT,SQRT(AMOUNT) AS SQUAREROOT_AMOUNT FROM INCOME_RECORD;
SELECT AMOUNT,AMOUNT*1.10 AS INCOME_BY_10PERCENT_INCREMENT FROM INCOME_RECORD;

SELECT CURDATE() AS TODAY_DATE;
SELECT NOW() AS CURRENT_DATE_TIME;
SELECT START_DATE,YEAR(START_DATE) AS YEAR FROM FINANCIAL_YEAR;
SELECT START_DATE,MONTH(START_DATE) AS MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DAY(START_DATE) AS DAY_OF_MONTH FROM FINANCIAL_YEAR;
SELECT START_DATE,DATE_ADD(START_DATE,INTERVAL 30 DAY) AS DATE_AFTER_30_DAYS FROM FINANCIAL_YEAR;
SELECT START_DATE, DATE_SUB(START_DATE,INTERVAL 7 DAY) AS DATE_BEFORE_7_DAYS FROM FINANCIAL_YEAR;
SELECT YEAR_LABEL,DATEDIFF(CURDATE(),START_DATE) AS DAYS_DIFF FROM FINANCIAL_YEAR;
SELECT * FROM FINANCIAL_YEAR WHERE YEAR (START_DATE)=YEAR(CURDATE());

SELECT CAST(AMOUNT AS SIGNED) AS INCOME_INTEGER FROM INCOME_RECORD;
SELECT CAST(taxpayer_id AS CHAR) AS TAXPAYER_ID_CHAR FROM TAXPAYER;
SELECT CAST(START_DATE AS DATETIME) AS START_DATETIME FROM FINANCIAL_YEAR;
SELECT CAST(AMOUNT AS DECIMAL(10,2)) AS INCOME_DECIMAL FROM INCOME_RECORD;
SELECT CAST(AMOUNT AS CHAR) AS INCOME_STRING FROM INCOME_RECORD;
SELECT taxpayer_id,CAST(AMOUNT AS DECIMAL(10,2))*0.10 AS TAX_AMOUNT FROM INCOME_RECORD;